# Generated by Django 5.2 on 2025-04-20 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], max_length=20)),
                ('property_type', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_piece', models.IntegerField()),
                ('outdoor_space', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('city', models.CharField()),
                ('district', models.CharField()),
                ('street_number', models.CharField()),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('uplaoaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hzone_app.listing')),
            ],
        ),
    ]
