# Generated by Django 5.2 on 2025-04-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzone_app', '0002_alter_listingimage_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(blank=True, null=True),
        ),
    ]
