# Generated by Django 5.2 on 2025-04-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzone_app', '0003_listing_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='uplaoaded_at',
            new_name='uploaded_at',
        ),
    ]
